# Generated by Django 5.2.7 on 2025-10-23 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='valor',
            field=models.CharField(default='GRATIS'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='lugar',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nombre',
            field=models.CharField(),
        ),
    ]
