# Generated by Django 5.2.7 on 2025-10-27 12:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_inscrito_inscripcion_inscrito_evento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inscrito',
            constraint=models.UniqueConstraint(fields=('usuario', 'evento'), name='unique_inscripcion'),
        ),
    ]
