# Generated by Django 5.2.7 on 2025-10-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_evento_valor_alter_evento_fecha_alter_evento_lugar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='valor',
            field=models.CharField(),
        ),
    ]
