# Generated by Django 5.2.7 on 2025-10-23 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_evento_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='cupos',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='valor',
            field=models.IntegerField(),
        ),
    ]
