# Generated by Django 5.2.7 on 2025-10-27 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_inscrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscrito',
            name='inscripcion',
            field=models.ManyToManyField(blank=True, to='core.evento'),
        ),
    ]
