# Generated by Django 5.2.7 on 2025-10-27 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_inscrito_inscripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscrito',
            name='inscripcion',
        ),
        migrations.AddField(
            model_name='inscrito',
            name='inscripcion',
            field=models.ForeignKey(blank=True, default='halloween', on_delete=django.db.models.deletion.CASCADE, to='core.evento'),
        ),
    ]
