# Generated by Django 5.2.7 on 2025-10-27 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_inscrito_inscripcion_inscrito_inscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscrito',
            name='inscripcion',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.evento'),
        ),
    ]
