# Generated by Django 5.2.7 on 2025-10-27 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_inscrito_inscripcion_inscrito_inscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscrito',
            name='inscripcion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.evento'),
        ),
    ]
