# Generated by Django 5.2.7 on 2025-10-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_inscrito_inscripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscrito',
            name='inscripcion',
        ),
        migrations.AddField(
            model_name='inscrito',
            name='inscripcion',
            field=models.ManyToManyField(blank=True, to='core.evento'),
        ),
    ]
